### PR TITLE
Fix GH-1300

### LINKED ISSUE #1300: Playground: Log tab breaks when running the code without `console.log` statement
Log tab breaks when running the code without `console.log` statement when clicking run dashed-line is displayed each time regardless there is new log statements or not.

image

**Repro:**
 - Go to playground
 - Click log tab **notice No logs statement is displayed.**
 - Click run with no `console.log` statements in the code **No logs statement disappear.**
 - Click Run multiple times, with each time new dashed line is displayed.
**Code**
```let isDone: boolean = false;```
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
- **No Logs** statement shouldn't be replaced when **Run** button is clicked without `console.log` statement for first time.
- No New dashed line displayed unless there is a change in `log` tab.
**Actual behavior:**
- **No logs** statement disappears when clicking **Run** for the first time.
- Dashed line is displayed regardless new log is appended or not.

### PR DESCRIPTION
**Pull request by hahmadia**
Fix https://github.com/microsoft/TypeScript-Website/issues/1300 by simplifying the clearing of console logic.

### CODE REVIEW

File: packages/playground/src/sidebar/runtime.ts [hunk 1]
```diff
@@ -94,19 +91,15 @@ function rewireLoggingToElement(
...
     obj[name] = function (...objs: any[]) {
       const output = produceOutput(objs)
       const eleLog = eleLocator()
       const prefix = `[<span class="log-${name}">${id}</span>]: `
       const eleContainerLog = eleOverflowLocator()
-      const index = cur - offset
-      if (index >= 0) {
-        allLogs[index] = (allLogs[index] ?? '') + prefix + output + "<br>"
-      }
+      allLogs.push(prefix + output + "<br>");
```
Comment (abdallamourad) [inline packages/playground/src/sidebar/runtime.ts]: Nit: This could be rewritten as
```suggestion
      allLogs.push(`${prefix}${output}<br>`);
```

**Comment by orta** [comment]
Interesting, yeah, this looks good to me thanks!
