### PR TITLE
Playground fixes

### LINKED ISSUE #908: Playground: Saving playground doesn't capture current code on document load
Type some stuff into

https://www.typescriptlang.org/play

Hit <kbd>Ctrl</kbd>+<kbd>S</kbd> or <kbd>Cmd</kbd>+<kbd>S</kbd> to save the URL.

Paste this URL somewhere.

Then navigate back to

https://www.typescriptlang.org/play

Don't type anything. Hit <kbd>Ctrl</kbd>+<kbd>S</kbd> or <kbd>Cmd</kbd>+<kbd>S</kbd> to save the URL.

The URLs end up not being the same; instead you'll get `https://www.typescriptlang.org/play`

### PR DESCRIPTION
**Pull request by orta**
Fixes #908 #901, and I think #900 is a dupe of #908 so fixes #908 too

### CODE REVIEW

File: packages/typescriptlang-org/src/templates/pages/community.tsx [hunk 1]
```diff
@@ -193,23 +182,21 @@ export const Comm: React.FC<Props> = props => {
...
-                      <img src={require("../../assets/community/meetup-logos/" + meetup.image)} className="icon img-square" alt={"logo of " + meetup.title} />
-                      <div>
-                        <h4 className="community-callout-headline">{meetup.title}</h4>
-                        <div className="text">{meetup.country}<br /><a rel="noopener" target="blank" href={meetup.url}>Website</a>{meetup.twitter ? <a rel="noopener" target="blank" href={meetup.twitter}>Twitter</a> : null}</div>
-                      </div>
-                    </Col>
-                  ))}
+
+          <div className="callouts">
+            {meetups.sort().map(m => m.meetup).map(meetup => (
```
Comment (DanielRosenwasser) [inline packages/typescriptlang-org/src/templates/pages/community.tsx:187]: 1. Is it okay that this mutates `meetups`?
2. If these are objects, what is this sorting by?
3. You can turn this into 1 `map` call
